version: "3.2"
services:

  all-in-one-redis:
    container_name: all-in-one-redis
    image: redis:latest
    restart: always
    command: redis-server /usr/local/etc/redis/redis.conf
    logging:
     driver: none
    ports:
      - "${REDIS_SERVICE_PORT}:6379"
    volumes:
      - "./redis:/usr/local/etc/redis"

  all-in-one-media:
    container_name: all-in-one-media
    restart: always
    image: "httpd:latest"
    logging:
      driver: none
    volumes:
      - "./media:/usr/local/apache2/htdocs"
    ports:
      - "${MEDIA_SERVICE_PORT}:80"          

  all-in-one-app:
    container_name: all-in-one-app
    restart: always
    build:
      context: ./app
      args:
        BUILD_ENV: $ENV        
        GROUP_ID: $GROUP_ID        
        USER_ID: $USER_ID
        USER_NAME: $USER_NAME
    image: all-in-one-app:latest
    environment:       
      FLASK_PORT: "${APP_SERVICE_PORT}"            
      FLASK_ENV: $ENV
      FLASK_APP: app.py
      DEFAULT_MEDIA_FOLDER: /usr/src/all-in-one/media/
      CELERY_RESULT_BACKEND: redis://all-in-one-redis:6379/0
      CELERY_BROKER_URL: redis://all-in-one-redis:6379/0  
    command: /usr/src/all-in-one/app/start      
    volumes:
      - "./app:/usr/src/all-in-one/app"      
      - "./media:/usr/src/all-in-one/media/"
    ports:
      - "${APP_SERVICE_PORT}:${APP_SERVICE_PORT}"
    depends_on:      
      - all-in-one-redis
      - all-in-one-media
    devices: 
      - /dev/gpiomem:/dev/gpiomem
      - /dev/mem:/dev/mem
      - /dev/video0:/dev/video0
      - /dev/vchiq:/dev/vchiq
      - /dev/vcsm:/dev/vcsm
    privileged: true

  all-in-one-app-worker:
    image: all-in-one-app:latest
    container_name: all-in-one-app-worker
    restart: always        
    environment:
      FLASK_PORT: "${APP_SERVICE_PORT}"            
      FLASK_ENV: $ENV
      FLASK_APP: app.py
      DEFAULT_MEDIA_FOLDER: /usr/src/all-in-one/media/
      CELERY_RESULT_BACKEND: redis://all-in-one-redis:6379/0
      CELERY_BROKER_URL: redis://all-in-one-redis:6379/0
    command: /usr/src/all-in-one/start_celery
    volumes:
      - "./app:/usr/src/all-in-one/app"      
      - "./media:/usr/src/all-in-one/media/"
    depends_on:
      - all-in-one-app
    privileged: true

  
